[package]
authors = ["Titan Class P/L"]
edition = "2018"
readme = "README.md"
name = "app"
version = "0.1.0"

[dependencies]
defmt = { version = "0.3", optional = true }
heapless = "0.7.7"

[dev-dependencies]
menu = "0.3.2"
pancurses = "0.17"
